from os.path import join, dirname


# Directories
RECIPES_DIR = join(dirname(dirname(__file__)), "recipes")


# Detection
DETECTION_FRAME_RESIZED_SHAPE = (320, 240)

BRICK_DISTANCE_MARGIN = 50

MINIMUM_BRICK_SIZE_PIXELS = 600

MOG2_SUBTRACTOR_HISTORY = 300

MOG2_SUBTRACTOR_VARIANCE_THRESHOLD = 180

NOISE_REDUCTION_KERNEL_SIZE = (3, 3)

MINIMUM_FRAMES_BETWEEN_PIECES = 10

CV_GREEN_COLOR = (0, 255, 0)
